apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orca-smoke-orc4
resources:
  - deployment.yaml
configMapGenerator:
  - name: go-orca-smoke
    files:
      - config.yaml
images:
  - name: go-orca-smoke
    newName: go-orca-smoke
    newTag: local
